# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_companyname', models.CharField(max_length=50)),
                ('contact_primary_fname', models.CharField(max_length=50)),
                ('contact_primary_lname', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_contact_no', models.CharField(max_length=20)),
                ('contact_state', models.CharField(max_length=50)),
                ('contact_country', models.CharField(max_length=50)),
                ('contact_address_lane', models.CharField(max_length=250)),
                ('contact_type', models.CharField(max_length=20)),
                ('contact_group', models.CharField(max_length=50)),
            ],
        ),
    ]
