# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcontacts',
            name='contact_country',
            field=models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('UK', 'UK'), ('Australia', 'Australia'), ('Sweden', 'Sweden')], max_length=50),
        ),
        migrations.AlterField(
            model_name='allcontacts',
            name='contact_state',
            field=models.CharField(choices=[('State1', 'State1'), ('State2', 'State2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='allcontacts',
            name='contact_type',
            field=models.CharField(choices=[('Consumer', 'Consumer'), ('Supplier', 'Supplier')], max_length=20),
        ),
    ]
