# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0002_auto_20170306_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allcontacts',
            old_name='contact_address_lane',
            new_name='Address_Lane',
        ),
        migrations.RenameField(
            model_name='allcontacts',
            old_name='contact_companyname',
            new_name='Company_Name',
        ),
        migrations.RenameField(
            model_name='allcontacts',
            old_name='contact_group',
            new_name='Contact_Group',
        ),
        migrations.RenameField(
            model_name='allcontacts',
            old_name='contact_contact_no',
            new_name='Contact_No',
        ),
        migrations.RenameField(
            model_name='allcontacts',
            old_name='contact_type',
            new_name='Contact_Type',
        ),
        migrations.RenameField(
            model_name='allcontacts',
            old_name='contact_country',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='allcontacts',
            old_name='contact_email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='allcontacts',
            old_name='contact_primary_fname',
            new_name='Primary_First_name',
        ),
        migrations.RenameField(
            model_name='allcontacts',
            old_name='contact_primary_lname',
            new_name='Primary_Last_name',
        ),
        migrations.RenameField(
            model_name='allcontacts',
            old_name='contact_state',
            new_name='State',
        ),
    ]
