# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0003_auto_20170306_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allcontacts',
            old_name='Address_Lane',
            new_name='Address',
        ),
        migrations.RemoveField(
            model_name='allcontacts',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='allcontacts',
            name='State',
        ),
        migrations.AddField(
            model_name='allcontacts',
            name='username',
            field=models.CharField(default='amaydefault', max_length=50),
            preserve_default=False,
        ),
    ]
