# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0004_auto_20170613_0755'),
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Due_Date', models.DateField()),
                ('References', models.CharField(max_length=50)),
                ('Amount', models.CharField(max_length=250)),
                ('From', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.AllContacts')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Due_Date', models.DateField()),
                ('References', models.CharField(max_length=250)),
                ('Amount', models.CharField(max_length=50)),
                ('To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.AllContacts')),
            ],
        ),
    ]
