# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=50)),
                ('Item_Code', models.CharField(max_length=50)),
                ('Unit_Price', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=100)),
                ('Purchases_Account', models.CharField(choices=[('Discount', 'Discount'), ('General Income', 'General Income'), ('Late Fee Income', 'Late Fee Income'), ('Interest Income', 'Interest Income'), ('Other Charges', 'Other Charges'), ('Sales', 'Sales'), ('Shipping Charge', 'Shipping Charge')], max_length=50)),
                ('Quantity', models.CharField(max_length=10)),
                ('Selling_Price', models.CharField(max_length=10)),
                ('Status', models.CharField(choices=[('Available', 'Available'), ('Out of Stock', 'Out of Stock')], max_length=20)),
                ('Tax_Rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.Tax')),
            ],
        ),
    ]
